# Generated by Django 4.0.2 on 2022-02-19 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='pubicado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
